---
- name: This is a Conjur Ansible integration demo
  hosts: localhost
  connection: local
  become: yes
  vars:
    nginx_private_key: "{{ lookup('cyberark.conjur.conjur_variable', 'cd/ansible/secrets/nginx_private_key') }}"
  tasks:
    - name: Lookup variable in Conjur
      debug:
        msg: "{{ nginx_private_key }}"

